### ISSUE TITLE
权限系统的设计

### ISSUE THREAD

**Issue by Menci** [syzoj/discussion#1]
# 权限
* **使用**：最基本的权限，对公开资源而言所有用户有权限使用，对未公开资源而言仅拥有**控制**权限的用户有权限使用。
* **控制**：能够对该资源进行除权限相关信息外的任意修改。
* **完全控制**：在**控制**的基础上，能够修改该资源的权限相关信息。

# 管理员
管理员分为两种：全站管理员（拥有除赋予/取消用户全站管理员权限外的任意权限）与普通管理员。

全站管理员拥有所有资源的**完全控制**权限，普通管理员拥有特定资源的**完全控制**权限，如：

* 用户（普通管理员仅拥有**控制**权限，即不可赋予/取消他人的管理员权限）
* 题目
* 比赛
* 讨论

# 用户组
每个用户组包含若干用户。

每个用户可属于多个用户组。

> 每个用户组有唯一的**属主**，属主可赋予/取消任意成员**用户组管理员**权限。
> 属主对用户组拥有**完全控制**权限，用户组管理员对用户组拥有**控制**权限（仅可添加、删除用户）

# 题目/比赛
每个题目/比赛具有唯一的属主。属主对该资源拥有**完全控制**权限，并可赋予任意用户组对该资源的**控制**权限。

> 拥有某场比赛权限的用户，仅可为该比赛添加其能够**使用**的题目。
> 比赛管理员对所有题目拥有**使用**权限。

**Comment by ksyx** [comment]
感觉这个用户组做起来就像是在 github 里面添加 collaborators。。只是把这个 collaborator 的列表一次性填好多次使用诶。。也就是说就是把一套权限配置存档了方便重复使用这种感觉

**Comment by Prurite** [comment]
prurite/syzoj 我做了一个简单的用户组系统，也许可以康康？

**Comment by Menci** [comment]
@Prurite 有些简陋吧，好多接口都没有实现

**Comment by Menci** [comment]
现在有一个问题就是，只能依次判断资源的每个授权组是否是在当前用户的用户组中，或者依次判断当前用户的每个用户组是否在资源的授权组中。如果数量比较大的话，会有严重的效率问题。

当然实际使用中应该不会很大量，但这也许是个安全隐患？

只允许该资源的管理员修改资源的授权组是不是更好？

**Comment by masnn** [comment]
建议参照vijos的用户角色设计
即支持定义角色，每种角色有特定权限
每个用户仅可以为某一种角色

**Comment by Menci** [comment]
主要是 loj 有时候需要资源级的权限控制，比如希望某一部分人可以修改一本通相关的题目
再比如之后可能会有允许一些人管理某场比赛，这样的操作

**Comment by StudyingFather** [comment]
如果用户组不是很多的话，感觉每个用户组都设一个属主是不是不太必要？

用户组成员管理可以交给普通用户管理员去做吧:thinking:

**Comment by Menci** [comment]
@StudyingFather 嗯，这部分是暂定的，可能确实不需要这么麻烦，之后可能会听听题库维护组的意见

**Comment by masnn** [comment]
> 主要是 loj 有时候需要资源级的权限控制，比如希望某一部分人可以修改一本通相关的题目
> 再比如之后可能会有允许一些人管理某场比赛，这样的操作

建议给题目分组，设计为题目组，同角色在不同题目组有不同权限

**Comment by Menci** [comment]
一个用户不应当只能有一种角色

比如让 A、B、C 用户管理讨论版，B、C、D 用户管理比赛，A 用户管理 { x, y, z } 这些题目

**Comment by masnn** [comment]
那么题目xyz为单独权限组，用户A在此权限组中拥有PERM_PROBLEM_MANAGE

其他题目为另一权限组，A 所在角色有 PERM_DISCUSSION_MANAGE
B,C 所在角色有 PERM_DISCUSSION_MANAGE与PERM_CONTEST_MANAGE
D 所在角色有 PERM_CONTEST_MANAGE

**Comment by Menci** [comment]
> 同角色在不同题目组有不同权限

是同用户在不同题目组有不同权限吧？

**Comment by Menci** [comment]
可以把两边都加上

* 用户属于用户组（不唯一）
* 题目属于题目组（唯一）
* 用户或用户组可以被 grant 一个题目或一个题目组的权限

**Comment by masnn** [comment]
合理
